/**
@file main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-10-24
@author Cristian Gantner

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/


/* Includes */
#include <stddef.h>
#include <string.h>
#include "stm32f10x.h"
#include "I2C_lib.h"
#include "USART_lib.h"

/* Private typedef */
/* Private define  */
const char StartChar = '[';
const char EndChar = 	']';

/* Private macro */
/* Private variables */
uint16_t recievedData;		/**< variable stores USART received bytes count */
uint8_t convDone = 0;		/**< status variable of conversion from ascii to hex */
uint8_t readData = 0;		/**< variable stores status if master should read from slave */
uint16_t readDataCount = 0;	/**< variable stores number of bytes to be read from slave */
uint8_t base = 16;			/**< stores base of hexadecimal system for conversion */
uint8_t pass;				/**< variable stores number of passes when converting hex value from ascii */

/* Private function prototypes */
void flush_i2cData();
void getDataCount();
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

int main(void){

	USART_init();
	Init_I2C();

	while (1)
	{
		if(newData){
			if((RecieveBuffer[0] == StartChar)&((RecieveBuffer[Write-1] == EndChar)|(RecieveBuffer[Write-2] == EndChar))){ 				//start of a command string
				recievedData = Write;
				while(Write){
					switch (RecieveBuffer[recievedData - Write + 1]){
					case ' ' :
						break;

					case '0':
						if(RecieveBuffer[recievedData - Write + 2] != 'x'){
							i2cData[i2cDataCount] += 0*base;
							base = 1;
							pass++;
						}
						break;

					case 'x':
						//start of hex value to be converted to dec
						base = 16;
						pass = 0;
						break;

					case 'r': //tells program how many bites should be received
						getDataCount();
						readData=1;
						break;

					case '1':
						i2cData[i2cDataCount] += 1*base;
						base = 1;
						pass++;
						break;

					case '2':
						i2cData[i2cDataCount] += 2*base;
						base = 1;
						pass++;
						break;

					case '3':
						i2cData[i2cDataCount] += 3*base;
						base = 1;
						pass++;
						break;

					case '4':
						i2cData[i2cDataCount] += 4*base;
						base = 1;
						pass++;
						break;

					case '5':
						i2cData[i2cDataCount] += 5*base;
						base = 1;
						pass++;
						break;

					case '6':
						i2cData[i2cDataCount] += 6*base;
						base = 1;
						pass++;
						break;

					case '7':
						i2cData[i2cDataCount] += 7*base;
						base = 1;
						pass++;
						break;

					case '8':
						i2cData[i2cDataCount] += 8*base;
						base = 1;
						pass++;
						break;

					case '9':
						i2cData[i2cDataCount] += 9*base;
						base = 1;
						pass++;
						break;

					case 'A':
						i2cData[i2cDataCount] += 10*base;
						base = 1;
						pass++;
						break;

					case 'B':
						i2cData[i2cDataCount] += 11*base;
						base = 1;
						pass++;
						break;

					case 'C':
						i2cData[i2cDataCount] += 12*base;
						base = 1;
						pass++;
						break;

					case 'D':
						i2cData[i2cDataCount] += 13*base;
						base = 1;
						pass++;
						break;

					case 'E':
						i2cData[i2cDataCount] += 14*base;
						base = 1;
						pass++;
						break;

					case 'F':
						i2cData[i2cDataCount] += 15*base;
						base = 1;
						pass++;
						break;

					case ']':
						newData = 0;
						convDone = 1;
						break;

					default:
						break;
					}
					if(pass>=2){
						i2cDataCount++;
						pass = 0;
					}
					Write--;
				}
			}

		}

		if((convDone & (readData != 1))){
			I2C_gatew_send();
			convDone = 0;
			flush_i2cData();
		}

		if((convDone & (readData == 1))){
			I2C_gatew_receive(readDataCount);
			readData = 0;
			convDone = 0;
			readDataCount = 0;
			i2cDataCount = 0;
			flush_i2cData();
		}

		//clear all status if wrong formated text received
		if((RecieveBuffer[0] != StartChar)&(newData)){
			readData = 0;
			convDone = 0;
			readDataCount = 0;
			i2cDataCount = 0;
			Write = 0;
			newData = 0;
			USART_sendString("Wrong data format.\n");
		}
	}
}

/**
 * @brief Function clears I2C data buffer.
 *
 * @param None
 * @return None
 */
void flush_i2cData(){
	uint8_t x;

	for(x=0; x<I2C_BUFFER_SIZE; x++){
		i2cData[x] = 0;
	}
}

/**
 * @brief Function calculates how many bytes should be read from slave and stores it in readDataCount variable.
 *
 * @param None
 * @return None
 */
void getDataCount(){
	uint8_t count[3]= {0xFF, 0xFF, 0xFF};
	uint8_t x=0;

	Write--;
	while((RecieveBuffer[recievedData - Write + 1]) != ']'){
		count[x] = ((RecieveBuffer[recievedData - Write + 1])-0x30);
		Write--;
		x++;
	}
	if(!(count[2]>9)){
		readDataCount = count[0]*100 + count[1]*10+ count[0];
	} else if(!(count[1]>9)){
		readDataCount = count[0]*10+ count[1];
	} else {
		readDataCount = count[0];}

	if(readDataCount>I2C_BUFFER_SIZE){readDataCount = I2C_BUFFER_SIZE;}
	Write++;
	i2cDataCount++;
}
